"""empty message

Revision ID: 070c489f14d9
Revises: 
Create Date: 2021-06-08 23:15:38.462608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070c489f14d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecturer',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('middlename', sa.String(length=80), nullable=True),
    sa.Column('passport_number', sa.Integer(), nullable=True),
    sa.Column('issued', sa.String(length=1000), nullable=True),
    sa.Column('adress', sa.String(length=1000), nullable=True),
    sa.Column('work', sa.String(length=1000), nullable=True),
    sa.Column('agreement_number', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('lecturer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lecturer')
    # ### end Alembic commands ###
