"""empty message

Revision ID: 0bc40772bd1f
Revises: 2431206f5bb8
Create Date: 2021-06-10 19:36:31.910360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc40772bd1f'
down_revision = '2431206f5bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
