"""empty message

Revision ID: 2431206f5bb8
Revises: 5f9107af33b6
Create Date: 2021-06-09 02:33:41.784613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2431206f5bb8'
down_revision = '5f9107af33b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('passport_who', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'passport_who')
    # ### end Alembic commands ###
