"""empty message

Revision ID: 38862834a46c
Revises: 0bc40772bd1f
Create Date: 2021-06-10 19:40:16.434803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38862834a46c'
down_revision = '0bc40772bd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'status')
    # ### end Alembic commands ###
