"""empty message

Revision ID: 486d530ff5d5
Revises: 070c489f14d9
Create Date: 2021-06-09 00:47:15.160351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486d530ff5d5'
down_revision = '070c489f14d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('birthday', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'birthday')
    # ### end Alembic commands ###
