"""empty message

Revision ID: 5550830cbc9f
Revises: 486d530ff5d5
Create Date: 2021-06-09 00:54:01.518906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5550830cbc9f'
down_revision = '486d530ff5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lecturer', sa.Column('rang', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lecturer', 'rang')
    # ### end Alembic commands ###
